// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJSizcT9pBEMSyoqkslfaIvWy_HC67D-E',
    appId: '1:798907010409:web:4138dfe9d36d83b178c1f8',
    messagingSenderId: '798907010409',
    projectId: 'portal-kinerja-gh2026',
    authDomain: 'portal-kinerja-gh2026.firebaseapp.com',
    storageBucket: 'portal-kinerja-gh2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8mqGrcjTyuj3BkaTmgZSWuNNi1yCewIA',
    appId: '1:798907010409:android:5c557d1d9008e5bc78c1f8',
    messagingSenderId: '798907010409',
    projectId: 'portal-kinerja-gh2026',
    storageBucket: 'portal-kinerja-gh2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoxupozER8X0SbQ0tSMZ3fOJctsG3JTro',
    appId: '1:798907010409:ios:72162efaf7cf001878c1f8',
    messagingSenderId: '798907010409',
    projectId: 'portal-kinerja-gh2026',
    storageBucket: 'portal-kinerja-gh2026.firebasestorage.app',
    iosBundleId: 'com.lapker.portalLapker',
  );
}
