// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Khusus Platform Web (Proyek Portal GH 2026)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy7AN4LM_34DvjSaig_0ItuJ_mxh-58DY',
    appId: '1:798907010409:web:4138dfe9d36d83b178c1f8',
    messagingSenderId: '798907010409',
    projectId: 'portal-kinerja-gh2026',
    authDomain: 'portal-kinerja-gh2026.firebaseapp.com',
    storageBucket: 'portal-kinerja-gh2026.firebasestorage.app',
  );
}
