// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy7AN4LM_34DvjSaig_0ItuJ_mxh-58DY',
    appId: '1:1011494856568:web:fcd99f8437ac4e0ce24a8d',
    messagingSenderId: '1011494856568',
    projectId: 'portal-lapker',
    authDomain: 'portal-lapker.firebaseapp.com',
    storageBucket: 'portal-lapker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApSrKt_BrYumvAs3lOrylUJIifFWZ0q38',
    appId: '1:1011494856568:android:dfdaef69cb429b2fe24a8d',
    messagingSenderId: '1011494856568',
    projectId: 'portal-lapker',
    storageBucket: 'portal-lapker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlNytOrCkaaVIQjRYaMT7o0JTme4CNQls',
    appId: '1:1011494856568:ios:37b9e472538c8c4fe24a8d',
    messagingSenderId: '1011494856568',
    projectId: 'portal-lapker',
    storageBucket: 'portal-lapker.firebasestorage.app',
    iosBundleId: 'com.lapker.portalLapker',
  );
}
